ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=bisellium
      export FLASK_ENV=development
      export PROMETHEUS_MULTIPROC_DIR=./prometheus_metrics
    init: |
      pip3 install -r requirements-dev.txt
      pip3 install -e .
    command: |
      flask run

vscode:
  extensions:
    - ms-python.python
    - DavidAnson.vscode-markdownlint
    - Gruntfuggly.todo-tree
    - shardulm94.trailing-spaces
    - eamodio.gitlens
